services:
    _defaults:
        autowire: true
        bind:
            $root_path: '%core.root_path%'
            $php_ext: '%core.php_ext%'
            $tables: '%tables%'

    kaileymsnay.pmrules.listener:
        class: kaileymsnay\pmrules\event\main_listener
        tags:
            - { name: event.listener }
